version: 2.1

orbs:
  docker: circleci/docker@0.5.2

workflows:
  build-deploy-pipeline:
    jobs:
      - build-push-image


jobs:
  build-push-image:
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: naceflabidi/graphql-sample:latest