version: 2.1

orbs:
  docker: circleci/docker@0.5.2
  helm: circleci/helm@0.1.2

workflows:
  build-deploy-pipeline:
    jobs:
      - build-push-image


jobs:
  build-push-image:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: naceflabidi/graphql-sample
      - docker/push:
          image: naceflabidi/graphql-sample

  deploy-chart:
    executor: docker/machine
    steps:
      - helm/install-helm-chart:
          chart: ./helm/graphql-sample
          namespace: graphql
          release-name: graphql
          tls-hostname: https://35.189.123.181